#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-multidict
Version  : 5.2.0
Release  : 42
URL      : https://files.pythonhosted.org/packages/8e/7c/e12a69795b7b7d5071614af2c691c97fbf16a2a513c66ec52dd7d0a115bb/multidict-5.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/8e/7c/e12a69795b7b7d5071614af2c691c97fbf16a2a513c66ec52dd7d0a115bb/multidict-5.2.0.tar.gz
Summary  : multidict implementation
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-multidict-license = %{version}-%{release}
Requires: pypi-multidict-python = %{version}-%{release}
Requires: pypi-multidict-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
Provides: multidict
Provides: multidict-python
Provides: multidict-python3
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)

%description
=========
multidict
=========
.. image:: https://github.com/aio-libs/multidict/workflows/CI/badge.svg
:target: https://github.com/aio-libs/multidict/actions?query=workflow%3ACI
:alt: GitHub status for master branch

%package license
Summary: license components for the pypi-multidict package.
Group: Default

%description license
license components for the pypi-multidict package.


%package python
Summary: python components for the pypi-multidict package.
Group: Default
Requires: pypi-multidict-python3 = %{version}-%{release}

%description python
python components for the pypi-multidict package.


%package python3
Summary: python3 components for the pypi-multidict package.
Group: Default
Requires: python3-core
Provides: pypi(multidict)

%description python3
python3 components for the pypi-multidict package.


%prep
%setup -q -n multidict-5.2.0
cd %{_builddir}/multidict-5.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641456744
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-multidict
cp %{_builddir}/multidict-5.2.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-multidict/02821ffe00e8c771ad89722cbe98e5d74ba36369
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-multidict/02821ffe00e8c771ad89722cbe98e5d74ba36369

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
